### ISSUE TITLE
AssertionError while running tests

### ISSUE THREAD

**Issue by housw** [jakobnissen/vamb#8]
Hi, 

here is the error I got while running runtests.py, hope it helps. 

```
(vamb):/vamb/test$ python runtests.py 
Traceback (most recent call last):
  File "runtests.py", line 4, in <module>
    import cluster
  File "/home/shengwei/anaconda3/envs/vamb/lib/python3.6/vamb/test/cluster.py", line 42, in <module>
    (54, {40, 54})]
AssertionError
```
Best, 
Shengwei

**Comment by jakobnissen** [comment]
Dear @housw 

I've just combed the tests through again, and everything works on my side. Did you test on the master or the dev branch? The dev branch had, until the commit two minutes ago (3 jan 10:52 CET), files which did not work given changes to the code on the dev branch.
If you tested on master version: Which version of Python, Numpy and PyTorch did you use?

**Comment by housw** [comment]
Hi, 
I'm using the master branch in a conda enviroment, here are the dependences:
```
(vamb) shengwei@kraken:~/anaconda3/envs/vamb/lib/python3.6/vamb/test$ conda env export 
name: vamb
channels:
  - hcc
  - biocore
  - bioconda
  - r
  - defaults
  - ursky
  - conda-forge
dependencies:
  - bcftools=1.9=h4da6232_0
  - htslib=1.9=hc238db4_4
  - libdeflate=1.0=h470a237_0
  - pysam=0.15.1=py36h0380709_0
  - samtools=1.9=h8ee4bcc_1
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29=py36_0
  - cffi=1.11.5=py36he75722e_1
  - cudnn=7.1.2=cuda9.0_0
  - curl=7.63.0=hbc83047_1000
  - intel-openmp=2019.1=144
  - krb5=1.16.1=h173b8e3_7
  - libcurl=7.63.0=h20c2e04_1000
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libssh2=1.8.0=h1ba5d50_4
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - openssl=1.1.1a=h7b6447c_0
  - pip=18.1=py36_0
  - pycparser=2.19=py36_0
  - python=3.6.7=h0371630_0
  - pytorch=0.4.1=py36ha74772b_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.6.3=py36_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - cudatoolkit=9.0=0
prefix: /home/shengwei/anaconda3/envs/vamb
```
Thanks, 
Shengwei

**Comment by jakobnissen** [comment]
I assume this bug is fixed by https://github.com/jakobnissen/vamb/commit/f7f9ceb788086a6a80a7ffe0c6209658126902a9 - but I was never able to recreate the bug on my own system, so I can't tell if it's fixed. I have updated the test accordingly on master branch.
